config/routes.rb
Rails.application.routes.draw do
  resources :groups, only: [:index]
  resources :projects
  resources :workers
  get '/groups/:id/workers', to: "groups#add_workers", as: "add_workers"
  post '/groups', to: "groups#update_project", as: "update_project"
  get '/projects/:id/add_workers', to: 'groups#workers'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
    belongs_to :project
    belongs_to :worker
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :groups
    has_many :workers, through: :groups
end

app/models/worker.rb
class Worker < ApplicationRecord
    has_many :groups
    has_many :projects, through: :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    def add_workers
        @project = Project.find(params[:id])
        @group = Group.new
        @workers = Worker.all
    end

    def update_project
        redirect_to project_path(@project)
    end

    def workers
        @project = Project.find(params[:id])
        render "add_workers"
    end 

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    def index
        @projects = Project.all
    end

    def show
        @project = Project.find(params[:id])
    end

    def edit
        @project = Project.find(params[:id])
    end

    def update
        @project = Project.find(params[:id])

        @project.update(project_params)

        redirect_to project_path(@project)
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.create(project_params)

        redirect_to project_path(@project)
    end

    def destroy 
        @project = Project.find(params[:id]) 
        @project.destroy 
        redirect_to projects_path 
    end 

    private

    def project_params
        params.require(:project).permit(:name, :details)
    end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
    def index
        @workers = Worker.all
    end

    def show
        @worker = Worker.find(params[:id])
    end

    def new
        @worker = Worker.new
    end

    def create
        @worker = Worker.create(worker_params)

        redirect_to worker_path(@worker)
    end

    def edit
        @worker = Worker.find(params[:id])
    end

    def update
        @worker = Worker.find(params[:id])

        @worker.update(worker_params)

        redirect_to worker_path(@worker)
    end

    def destroy
        @worker = Worker.find(params[:id])
        @worker.destroy
        redirect_to workers_path 
    end 

    private

    def worker_params
        params.require(:worker).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/groups/add_workers.html.erb
<h1>Add Workers to <%=@project.name%></h1>

<%= form_for @project, :url => add_workers_path do |p| %>
    <%= p.collection_check_boxes(:worker_ids, Worker.all, :id, :name) %>
    <%= p.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdealWorkApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form_project.html.erb
<%= form_for @project do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :details %>
    <%= f.text_area :details %>
    <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project Form</h1>

<%= render 'form_project' %>

app/views/projects/index.html.erb
<h1>All the Projects</h1>

<ul>
<% @projects.each do |proj| %>
    <li>
        <%= link_to proj.name, project_path(proj) %>
    </li>
<% end %>
</ul>

<%= link_to 'Make New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project Form</h1>

<%= render 'form_project' %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>

<h3><%= @project.details %></h3>

<ul>
<% @project.groups.each do |g| %>
    <li><%= g.type %>: <%= g.worker.name %></li>
<% end %>
</ul>


<%= link_to 'Add Peoples', add_workers_path(@project) %>
<%= link_to 'Go Home', projects_path %>
<%= link_to 'Edit This Project', edit_project_path(@project) %>
<%= link_to 'Destroy This Project', project_path(@project), :method => 'delete' %> 

app/views/workers/_form_worker.html.erb
<%= form_for @worker do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :age %>
    <%= f.number_field :age %>
    <%= f.submit %>
<% end %>

app/views/workers/edit.html.erb
<h1>Edit Worker Form</h1>

<%= render 'form_worker' %>

app/views/workers/index.html.erb
<h1>All the Workers!</h1>

<ul>
<% @workers.each do |work| %>
    <li>
        <%= link_to work.name, worker_path(work) %>
    </li>
<% end %>
</ul>

<%= link_to 'New Worker Form',new_worker_path %>

app/views/workers/new.html.erb
<h1>New Worker Form</h1>
<%= render 'form_worker'  %>

app/views/workers/show.html.erb
<h1><%= @worker.name %></h1>
<h2>Age: <%= @worker.age %></h2>

<%= link_to 'Edit Worker', edit_worker_path(@worker) %>
<%= link_to 'Go Back Home', workers_path %>
<%= link_to 'Delete This Worker', worker_path(@worker), :method => 'delete' %>